# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82e7283cc095f7a362d42187e5fd745fb28f1c74524b7fef02571fd067ae436528190a0f38a81351f47ae54bf2defcdaa3813e6cc0ba9851ceaaad7ec85a5ccd

test:
  secret_key_base: a937a99f0dea96023913d7be3d90b2703cf91025f5f90a6ec3f9373d3c385e8df0b43c4944e6917f0130bcef846960378e3c24df7c15d3607503478f2034ea4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
